---
name: Build/Push Development Images
env:
  LC_ALL: "C.UTF-8" # prevent ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
  PLATFORMS: linux/amd64,linux/arm64
on:
  push:
    branches:
      - devel
      - release_*
      - feature_*
jobs:
  push:
    if: endsWith(github.repository, '/awx') || startsWith(github.ref, 'refs/heads/release_')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Get python version from Makefile
        run: echo py_version=`make PYTHON_VERSION` >> $GITHUB_ENV

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Install python ${{ env.py_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.py_version }}

      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pre-pull image to warm build cache
        run: |
          docker pull ghcr.io/${OWNER_LC}/awx_devel:${GITHUB_REF##*/} || :
          docker pull ghcr.io/${OWNER_LC}/awx_kube_devel:${GITHUB_REF##*/} || :
          docker pull ghcr.io/${OWNER_LC}/awx:${GITHUB_REF##*/} || :

      - name: Build and push AWX development environment images
        run: |
          make docker-compose-buildx
          make awx-kube-dev-buildx
          make awx-kube-buildx
        env:
          DEV_DOCKER_TAG_BASE: ghcr.io/${OWNER_LC}
          COMPOSE_TAG: ${GITHUB_REF##*/}

      - name: Build and push images AWX images
        run: |
          make awx-kube-buildx
        env:
          DEV_DOCKER_TAG_BASE: ghcr.io/${OWNER_LC}
          COMPOSE_TAG: ${GITHUB_REF##*/}
        if: endsWith(github.repository, '/awx')
